<a href="https://colab.research.google.com/github/gshaurya27/SOC-26---Face-Ageing-Model/blob/main/WEEK%202%20/TensorFlow/02_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf

In [10]:
#initisializing
x1 = tf.constant(4, shape=(1,1), dtype=tf.float32)
x2 = tf.constant([[1,2,3],[4,5,6]]) #2 by 3 matrix
x3 = tf.ones((3,3))
x3 = tf.eye(3)
x4 = tf.random.normal((3,3), mean=0, stddev=1)
x5 = tf.random.uniform((1,3), minval=0, maxval=1)
x6 = tf.range(9)
print(x1)
print(x2)
print(x3)
print(x4)
print(x5)
print(x6)


tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-1.6704966   0.64337546 -0.74626523]
 [-1.1351167  -0.10114916  0.1310343 ]
 [ 0.60117596 -0.03420344  0.8976866 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.38886344 0.6600101  0.3872205 ]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [14]:
#mathematical ope

x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z1 = tf.add(x,y)
z1 = x+y
z2 = tf.subtract(x,y)
z2 = x-y
z3 = tf.divide(x,y)
z3 = x/y
z4 = tf.multiply(x,y)
z4 = x*y
print(z4)

z5 = tf.tensordot(x,y, axes=1)
print(z5)

z6 = x**5
print(z6)

x = tf.reshape(x, (1,3))
y = tf.reshape(y, (3,1))
z7 = tf.matmul(x,y)
z7 = x@y
print(z7)


tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor([[46]], shape=(1, 1), dtype=int32)


In [21]:
#indexing
x = tf.constant([0,1,2,3,4,5,6,7])
print(x[:])
print(x[1:])
print(x[1:5])
print(x[::2])
print(x[::-1])
print(' ')

indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([0 2 4 6], shape=(4,), dtype=int32)
tf.Tensor([7 6 5 4 3 2 1 0], shape=(8,), dtype=int32)
 
tf.Tensor([0 3], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [22]:
#reshaping
x = tf.range(9)
x = tf.reshape(x, (3,3))
print(x)
print(tf.transpose(x, perm=[1,0]))
print(tf.transpose(x, perm=[0,1]))
#

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
